"""Fixture-parity test: `ocg_rf_listener.canon` MUST reproduce, byte-for-byte,
the canonical preimage + execution_hash produced by the real
`chaingraph/kernels/_hash.mjs` (cgCanon / executionHash). Fixtures in
`fixtures/canon_fixtures.json` were generated by running that exact JS module
against the cases below -- see the header comment in that file's generator
note in README.md SS"Fixture provenance". If this test goes red, canon.py has
drifted from the canonical JS lineage; fix canon.py, never the fixtures.
"""

import json
from pathlib import Path

from ocg_rf_listener.canon import canonical_preimage, execution_hash

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "canon_fixtures.json"


def _load_fixtures():
    with open(FIXTURES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def test_fixtures_file_present():
    fixtures = _load_fixtures()
    assert len(fixtures) >= 3


def test_canonical_preimage_matches_js_lineage():
    for case in _load_fixtures():
        actual = canonical_preimage(case["policy_parameters"], case["output_payload"])
        assert actual == case["preimage"], f"preimage mismatch for case: {case['output_payload']}"


def test_execution_hash_matches_js_lineage():
    for case in _load_fixtures():
        actual = execution_hash(case["policy_parameters"], case["output_payload"])
        assert actual == case["execution_hash"], f"hash mismatch for case: {case['output_payload']}"


def test_key_sort_and_array_order():
    payload = {"z": 1, "a": 2, "arr": [3, 1, 2]}
    preimage = canonical_preimage({}, payload)
    assert preimage == '{"output_payload":{"a":2,"arr":[3,1,2],"z":1},"policy_parameters":{}}'


def test_hash_is_deterministic():
    payload = {"suite": {"name": "X"}}
    assert execution_hash({}, payload) == execution_hash({}, payload)
